### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by willieLjohnson** [MakeSchool-Tutorials/Make-Cookies#1]
- **P00**
  - Grammar in sentence before user stories:  "Here **is are** a few user stories for Make Cookies."
  - Like how you introduce HTML Boilerplates.
- **P01**
  - Like your use of ellipsis in code blocks, but it seems a bit inconsistent because some don't have them.
  - Got a bit confused in the transition from "Make Some Cookies!" to "Tracking our cookies!". In "Tracking our Cookies!" we add the lines:
  ```
  //declare default variables
  let cookieCount = 0;
  ```
  However, in the next code block the comment above `let cookieCount = 0;` changes and becomes `//set default variables`. This made me feel lost during "Make Some Cookies!"
    - Also, the line `cookieCounter.innerHTML = cookieCount;` disappears. I'm assuming that it's replaced by what we add in the next step, but there is no mention of this. 
  - There's only syntax highlighting in a few code blocks.
- **P02**
  - Grammar in sentence describing markup needed for game: "[...] and **how much many** cookies they can produce."
  - In "Making our shop work!" it says, "Next we can **_add_ a line** of JavaScript to take away cookies based on the price," but multiple lines are added and the resulting code shows that the `console.log` statements were _replaced_.
- **P04**
  - Last step in "Adding our on click function" was a bit confusing as one of the comments says `//DONT FORGET THIS BRACKET AT THE END OF THE ENTIRE BUY FUNCTION`. Is there a better way to note this? Like, "make sure you include your comments from the previous step in this if statement"
  - maybe you can just show a bit more like, 
     ```js
      // Make sure we have enough cookies and subtract our cookies from the price.
      if (cookieCount >= grandmaPriceAmount) {
        // Subtract cookies from the price of the item.
        cookieCount +=  - grandmaPriceAmount;
        refreshCookieCount()
    
        // Upgrade power level.

        // Update price.

        ...
      }
     ```
- **P05**
  - Doesn't say where the markup for the Cookie Manufacturing Facilities should go.
  - There's an unnecessary closing brace at the end of the `buyFacility.addEventListener`, and it shows up again in the next code block.
      ```js
      ...
        //refresh shop item

          }//DONT FORGET THIS BRACKET
        } **<--- unneeded**
      })
      ```
   - The variable  `facilityAuto` changes to `autoFacility`:
      ```js
      ...
      //turn autoFacility on!
      autoFacility = true **<--- should be facilityAuto, also missing semicolon**
      autoFacilityStart();
      ```
- Overall, good tutorial and fun game. Only problems were with inconsistency and grammar.

**Comment by joerez** [comment]
Thanks so much for the feedback. That was excellent.
